version: '2'
services:
    referencedata-app:
        image: referencedata
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://referencedata-postgresql:5432/referencedata
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    referencedata-postgresql:
        extends:
            file: postgresql.yml
            service: referencedata-postgresql
